server:
  port: 8080
hm:
  jwt:
    location: classpath:hmall.jks
    alias: "***"
    password: "***"
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi